kind: pipeline
name: default

steps:
- name: test
  image: golang:1.10-alpine
  commands:
  - "go test"

- name: build
  image: golang:1.10-alpine
  commands:
  - "go build -o ./myapp"
  
- name: create releaselog
  image: quay.io/git-chglog/git-chglog:latest
  commands:
    - "git fetch origin --prune --tags"
    - "git-chglog ${DRONE_TAG} > RELEASELOG.md"
  when:
    event: tag
  
- name: publish
  image: plugins/github-release
  settings:
    tags: ${DRONE_TAG##v}
    api_key:
      from_secret: github_token
    files:
      - ./myapp
      - RELEASELOG.md
    note: RELEASELOG.md
    title: "Version ${DRONE_TAG}"
    overwrite: true
    checksum:
      - sha512
  when:
    event: tag
