kind: pipeline
name: main
type: docker

steps:
  - name: test
    image: golang:1.10-alpine
    commands:
    - "go test"

  - name: build
    image: golang:1.10-alpine
    commands:
    - "go build -o ./myapp"
    -
  - name: cache package
    image: curlimages/curl:7.77.0
    environment:
      PASSWORD:
        from_secret: drone_upload_password
      USERNAME:
        from_secret: drone_upload_username
      COMMIT: DRONE_COMMIT
    commands:
      - "tar -czvf ~/$COMMIT.tar.gz ./myapp"
      - "curl -i -u $USERNAME:$PASSWORD -F file=~/$COMMIT.tar.gz https://upload.bohicalabs.com"

  - name: generate releaselog
    image: quay.io/git-chglog/git-chglog:latest
    commands:
      - "git fetch origin --prune --tags"
      - "git-chglog ${DRONE_TAG} > RELEASELOG.md"
    when:
      event: tag

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: global_github_token
      files:
        - ./myapp
        - RELEASELOG.md
      note: RELEASELOG.md
      title: "Release ${DRONE_TAG}"
      overwrite: true
      checksum:
        - sha512
    when:
      event: tag

---
kind: pipeline
name: changelog
type: docker

clone:
  disable: true

steps:
  - name: clone
    image: plugins/git-action:1
    settings:
      actions:
        - clone
      remote: ${DRONE_GIT_HTTP_URL}
      branch: master
      path: /drone/src
      netrc_machine: github.com
      netrc_username:
        form_secret: global_github_username
      netrc_password:
        form_secret: global_github_token

  - name: generate
    image: quay.io/git-chglog/git-chglog:latest
    commands:
      - "git fetch origin --prune --tags"
      - "git-chglog > CHANGELOG.md"
    when:
      event: tag

  - name: diff
    image: alpine/git:latest
    commands:
      - "git diff"

  - name: output
    image: alpine:latest
    commands:
      - "cat CHANGELOG.md"

  - name: publish
    image: plugins/git-action:1
    settings:
      actions:
        - commit
        - push
      message: "docs(changelog): auto changelog update ${DRONE_TAG} [CI SKIP]"
      author_email: devops@bohicalabs.com
      author_name: bohicalabs
      branch: master
      path: /drone/src
      netrc_machine: github.com
      netrc_username:
        from_secret: global_github_username
      netrc_password:
        from_secret: global_github_token

trigger:
  event:
    - tag
  ref:
    - refs/heads/master
    - refs/tags/*

---
kind: pipeline
name: mirroring
type: docker

clone:
  disable: true

steps:
  - name: mirror
    image: bohicalabs/drone-git-mirror:1.0.7
    settings:
      target_repo: github.com/drbothen/droneTest2.git
      git_domain: github.com
      git_username:
        from_secret: github_username
      git_password:
        from_secret: github_password
trigger:
  repo:
    - drbothen/droneTest