kind: pipeline
type: kubernetes
name: tools

steps:
- name: test
  image: golang:1.10-alpine
  commands:
  - "go test"

- name: build
  image: golang:1.10-alpine
  commands:
  - "go build -o ./myapp"
