kind: pipeline
name: default

steps:
- name: test
  image: golang:1.10-alpine
  commands:
  - "go test"

- name: build
  image: golang:1.10-alpine
  commands:
  - "go build -o ./myapp"
  
- name: create_changelog
  image: quay.io/git-chglog/git-chglog:latest
  commands:
    - "apk --update add git less openssh"
    - "git fetch origin --prune --tags"
    - "git-chglog ${DRONE_TAG} > CHANGELOG.md"
  when:
    event: tag
  
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: ./myapp
    note: CHANGELOG.md
    title: "Version ${DRONE_TAG##v}"
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
  when:
    event: tag
