kind: pipeline
name: default

steps:
- name: test
  image: golang:1.10-alpine
  commands:
  - "go test"

- name: build
  image: golang:1.10-alpine
  commands:
  - "go build -o ./myapp"
  
 - name: create_changelog
   image: naorlivne/drone-github-changelog-generator
   settings:
     github_user: BOHICA LABS
     github_project: DroneTest
     output_path: CHANGELOG.md
   when:
     event: tag
  
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: ./myapp
    note: CHANGELOG.md
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
  when:
    event: tag
